/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnidadesRouteImport } from './routes/unidades'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as FuncionariosRouteImport } from './routes/funcionarios'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EquipamentosRouteImport } from './routes/equipamentos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ChecklistsRouteImport } from './routes/checklists'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PmocsIndexRouteImport } from './routes/pmocs.index'
import { Route as ValidarEquipamentoIdRouteImport } from './routes/validar.$equipamentoId'
import { Route as PmocsPmocIdRouteImport } from './routes/pmocs.$pmocId'
import { Route as EquipamentosEquipamentoIdRouteImport } from './routes/equipamentos.$equipamentoId'
import { Route as ApiPublicEquipamentoEquipamentoIdRouteImport } from './routes/api/public/equipamento.$equipamentoId'

const UnidadesRoute = UnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const FuncionariosRoute = FuncionariosRouteImport.update({
  id: '/funcionarios',
  path: '/funcionarios',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosRoute = EquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsRoute = ChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PmocsIndexRoute = PmocsIndexRouteImport.update({
  id: '/pmocs/',
  path: '/pmocs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidarEquipamentoIdRoute = ValidarEquipamentoIdRouteImport.update({
  id: '/validar/$equipamentoId',
  path: '/validar/$equipamentoId',
  getParentRoute: () => rootRouteImport,
} as any)
const PmocsPmocIdRoute = PmocsPmocIdRouteImport.update({
  id: '/pmocs/$pmocId',
  path: '/pmocs/$pmocId',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosEquipamentoIdRoute =
  EquipamentosEquipamentoIdRouteImport.update({
    id: '/$equipamentoId',
    path: '/$equipamentoId',
    getParentRoute: () => EquipamentosRoute,
  } as any)
const ApiPublicEquipamentoEquipamentoIdRoute =
  ApiPublicEquipamentoEquipamentoIdRouteImport.update({
    id: '/api/public/equipamento/$equipamentoId',
    path: '/api/public/equipamento/$equipamentoId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checklists': typeof ChecklistsRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/equipamentos': typeof EquipamentosRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/funcionarios': typeof FuncionariosRoute
  '/logs': typeof LogsRoute
  '/notificacoes': typeof NotificacoesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unidades': typeof UnidadesRoute
  '/equipamentos/$equipamentoId': typeof EquipamentosEquipamentoIdRoute
  '/pmocs/$pmocId': typeof PmocsPmocIdRoute
  '/validar/$equipamentoId': typeof ValidarEquipamentoIdRoute
  '/pmocs/': typeof PmocsIndexRoute
  '/api/public/equipamento/$equipamentoId': typeof ApiPublicEquipamentoEquipamentoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checklists': typeof ChecklistsRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/equipamentos': typeof EquipamentosRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/funcionarios': typeof FuncionariosRoute
  '/logs': typeof LogsRoute
  '/notificacoes': typeof NotificacoesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unidades': typeof UnidadesRoute
  '/equipamentos/$equipamentoId': typeof EquipamentosEquipamentoIdRoute
  '/pmocs/$pmocId': typeof PmocsPmocIdRoute
  '/validar/$equipamentoId': typeof ValidarEquipamentoIdRoute
  '/pmocs': typeof PmocsIndexRoute
  '/api/public/equipamento/$equipamentoId': typeof ApiPublicEquipamentoEquipamentoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/checklists': typeof ChecklistsRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/equipamentos': typeof EquipamentosRouteWithChildren
  '/financeiro': typeof FinanceiroRoute
  '/funcionarios': typeof FuncionariosRoute
  '/logs': typeof LogsRoute
  '/notificacoes': typeof NotificacoesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/unidades': typeof UnidadesRoute
  '/equipamentos/$equipamentoId': typeof EquipamentosEquipamentoIdRoute
  '/pmocs/$pmocId': typeof PmocsPmocIdRoute
  '/validar/$equipamentoId': typeof ValidarEquipamentoIdRoute
  '/pmocs/': typeof PmocsIndexRoute
  '/api/public/equipamento/$equipamentoId': typeof ApiPublicEquipamentoEquipamentoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/auth'
    | '/checklists'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/equipamentos'
    | '/financeiro'
    | '/funcionarios'
    | '/logs'
    | '/notificacoes'
    | '/reset-password'
    | '/unidades'
    | '/equipamentos/$equipamentoId'
    | '/pmocs/$pmocId'
    | '/validar/$equipamentoId'
    | '/pmocs/'
    | '/api/public/equipamento/$equipamentoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/auth'
    | '/checklists'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/equipamentos'
    | '/financeiro'
    | '/funcionarios'
    | '/logs'
    | '/notificacoes'
    | '/reset-password'
    | '/unidades'
    | '/equipamentos/$equipamentoId'
    | '/pmocs/$pmocId'
    | '/validar/$equipamentoId'
    | '/pmocs'
    | '/api/public/equipamento/$equipamentoId'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/auth'
    | '/checklists'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/equipamentos'
    | '/financeiro'
    | '/funcionarios'
    | '/logs'
    | '/notificacoes'
    | '/reset-password'
    | '/unidades'
    | '/equipamentos/$equipamentoId'
    | '/pmocs/$pmocId'
    | '/validar/$equipamentoId'
    | '/pmocs/'
    | '/api/public/equipamento/$equipamentoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ChecklistsRoute: typeof ChecklistsRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  EquipamentosRoute: typeof EquipamentosRouteWithChildren
  FinanceiroRoute: typeof FinanceiroRoute
  FuncionariosRoute: typeof FuncionariosRoute
  LogsRoute: typeof LogsRoute
  NotificacoesRoute: typeof NotificacoesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  UnidadesRoute: typeof UnidadesRoute
  PmocsPmocIdRoute: typeof PmocsPmocIdRoute
  ValidarEquipamentoIdRoute: typeof ValidarEquipamentoIdRoute
  PmocsIndexRoute: typeof PmocsIndexRoute
  ApiPublicEquipamentoEquipamentoIdRoute: typeof ApiPublicEquipamentoEquipamentoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unidades': {
      id: '/unidades'
      path: '/unidades'
      fullPath: '/unidades'
      preLoaderRoute: typeof UnidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funcionarios': {
      id: '/funcionarios'
      path: '/funcionarios'
      fullPath: '/funcionarios'
      preLoaderRoute: typeof FuncionariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos': {
      id: '/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof EquipamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists': {
      id: '/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof ChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pmocs/': {
      id: '/pmocs/'
      path: '/pmocs'
      fullPath: '/pmocs/'
      preLoaderRoute: typeof PmocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validar/$equipamentoId': {
      id: '/validar/$equipamentoId'
      path: '/validar/$equipamentoId'
      fullPath: '/validar/$equipamentoId'
      preLoaderRoute: typeof ValidarEquipamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pmocs/$pmocId': {
      id: '/pmocs/$pmocId'
      path: '/pmocs/$pmocId'
      fullPath: '/pmocs/$pmocId'
      preLoaderRoute: typeof PmocsPmocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos/$equipamentoId': {
      id: '/equipamentos/$equipamentoId'
      path: '/$equipamentoId'
      fullPath: '/equipamentos/$equipamentoId'
      preLoaderRoute: typeof EquipamentosEquipamentoIdRouteImport
      parentRoute: typeof EquipamentosRoute
    }
    '/api/public/equipamento/$equipamentoId': {
      id: '/api/public/equipamento/$equipamentoId'
      path: '/api/public/equipamento/$equipamentoId'
      fullPath: '/api/public/equipamento/$equipamentoId'
      preLoaderRoute: typeof ApiPublicEquipamentoEquipamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EquipamentosRouteChildren {
  EquipamentosEquipamentoIdRoute: typeof EquipamentosEquipamentoIdRoute
}

const EquipamentosRouteChildren: EquipamentosRouteChildren = {
  EquipamentosEquipamentoIdRoute: EquipamentosEquipamentoIdRoute,
}

const EquipamentosRouteWithChildren = EquipamentosRoute._addFileChildren(
  EquipamentosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ChecklistsRoute: ChecklistsRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  EquipamentosRoute: EquipamentosRouteWithChildren,
  FinanceiroRoute: FinanceiroRoute,
  FuncionariosRoute: FuncionariosRoute,
  LogsRoute: LogsRoute,
  NotificacoesRoute: NotificacoesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  UnidadesRoute: UnidadesRoute,
  PmocsPmocIdRoute: PmocsPmocIdRoute,
  ValidarEquipamentoIdRoute: ValidarEquipamentoIdRoute,
  PmocsIndexRoute: PmocsIndexRoute,
  ApiPublicEquipamentoEquipamentoIdRoute:
    ApiPublicEquipamentoEquipamentoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
